### ISSUE TITLE
Nothing showing up

### ISSUE THREAD

**Issue by ghost** [t0mj/Tasker#4]
Sorry for leaving this issue here but I had no way to contact the owner of the Tasker so here it is;
I don't know why but when I run any of those scripts, nothing shows up in the terminal and my question is, how does this tasker exactly works? How to start it up?
Thanks.

**Comment by t0mj** [comment]
You will need to install it as a package.  Did you try doing `pip install .` inside the repo?

**Comment by ghost** [comment]
Thats exactly what I did. I was trying to install this using different methods aswell, modifying some code and none of it works, any other ideas?

**Comment by t0mj** [comment]
When you type pip list do you see Tasker (1.4) in that list?

**Comment by ghost** [comment]
Yeah, I think the tasker was successfully installed in my system because it is on the list, but running the scripts doesn't really do anything

**Comment by t0mj** [comment]
Once its installed you shouldnt have to do anything with the scripts try just type `task` or `task --help` on the command line.

**Comment by ghost** [comment]
"bash: task: command not found" but thanks for help, I'll try to think of something

**Comment by t0mj** [comment]
Thats strange are you using a virtualenv?

**Comment by ghost** [comment]
Nope. I really wanted to try and implement Tasker with my personal assistant I am working on so I even went as far as reinstalling debian again, still nothing...

**Comment by t0mj** [comment]
I've only tested it in mac osx but a friend of mine tested it on ubuntu and was able to get it to work.  Sorry I may not be much more help to you but I wrote it around this package: http://click.pocoo.org/5/ 

They might have some docs to help you implement it with your other code or to get it working.

**Comment by ghost** [comment]
Weird cause packages and other things designed for ubuntu should work under debian and vice versa as ubuntu was build on foundations of debian, but thanks anyway, I'll try to write something like tasker, because it looks pretty cool
